//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool (Visual Studio "Add Service Reference").
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapClient.SOAPService
{
    using System.Runtime.Serialization;
    using System;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Customers", Namespace = "http://schemas.datacontract.org/2004/07/WCFSOAPWebService.DataModels")]
    [System.SerializableAttribute()]
    public partial class Customers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerCityField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get { return this.extensionDataField; }
            set { this.extensionDataField = value; }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerCity
        {
            get { return this.CustomerCityField; }
            set
            {
                if ((object.ReferenceEquals(this.CustomerCityField, value) != true))
                {
                    this.CustomerCityField = value;
                    this.RaisePropertyChanged("CustomerCity");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID
        {
            get { return this.CustomerIDField; }
            set
            {
                if ((this.CustomerIDField.Equals(value) != true))
                {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName
        {
            get { return this.CustomerNameField; }
            set
            {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true))
                {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "SOAPService.ISOAPService")]
    public interface ISOAPService
    {
        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ISOAPService/GetCustomers", ReplyAction = "http://tempuri.org/ISOAPService/GetCustomersResponse")]
        SoapClient.SOAPService.Customers[] GetCustomers();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ISOAPService/GetCustomers", ReplyAction = "http://tempuri.org/ISOAPService/GetCustomersResponse")]
        System.Threading.Tasks.Task<SoapClient.SOAPService.Customers[]> GetCustomersAsync();
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISOAPServiceChannel : SoapClient.SOAPService.ISOAPService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SOAPServiceClient : System.ServiceModel.ClientBase<SoapClient.SOAPService.ISOAPService>, SoapClient.SOAPService.ISOAPService
    {
        public SOAPServiceClient()
        {
        }

        public SOAPServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public SOAPServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public SOAPServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public SOAPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public SoapClient.SOAPService.Customers[] GetCustomers()
        {
            return base.Channel.GetCustomers();
        }

        public System.Threading.Tasks.Task<SoapClient.SOAPService.Customers[]> GetCustomersAsync()
        {
            return base.Channel.GetCustomersAsync();
        }
    }
}
